import{buildMeshes,translate,scale,multiply,ortho,normal3}from'./board3d-meshes.js';
const canvas=document.querySelector('#board-3d'),board=document.querySelector('#board'),stage=document.querySelector('.board-stage');
if(!canvas||!board||!stage)throw new Error('Crownforge WebGL elements missing');
const gl=canvas.getContext('webgl2',{alpha:true,antialias:true,depth:true,premultipliedAlpha:true,powerPreference:'high-performance'});
if(!gl){document.documentElement.classList.add('webgl-3d-unavailable')}else try{start(gl)}catch(e){document.documentElement.classList.add('webgl-3d-unavailable');console.warn('Crownforge WebGL disabled',e)}

function start(g){
  const vs=`#version 300 es\nprecision highp float;layout(location=0)in vec3 p;layout(location=1)in vec3 n;uniform mat4 M,VP;uniform mat3 N;out vec3 vN,vP;void main(){vec4 w=M*vec4(p,1);vP=w.xyz;vN=normalize(N*n);gl_Position=VP*w;}`;
  const fs=`#version 300 es\nprecision highp float;in vec3 vN,vP;uniform vec3 base,shine;uniform float gloss;out vec4 o;void main(){vec3 n=normalize(vN),l=normalize(vec3(-.48,.72,1.15)),v=vec3(0,0,1),h=normalize(l+v);float d=max(dot(n,l),0.),s=pow(max(dot(n,h),0.),mix(18.,58.,gloss)),r=pow(1.-max(dot(n,v),0.),2.2);vec3 c=base*(.34+.72*d)+shine*(s*(.25+.55*gloss)+.08*r);o=vec4(c,1);}`;
  const prog=program(g,vs,fs),u={M:g.getUniformLocation(prog,'M'),VP:g.getUniformLocation(prog,'VP'),N:g.getUniformLocation(prog,'N'),base:g.getUniformLocation(prog,'base'),shine:g.getUniformLocation(prog,'shine'),gloss:g.getUniformLocation(prog,'gloss')},meshes=buildMeshes(g),VP=ortho(-4,4,-4,4,-8,8);
  let locked=false,last='';
  g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.clearColor(0,0,0,0);
  function lock(){if(locked||board.dataset.geometryLocked!=='true')return false;const s=stage.getBoundingClientRect(),b=board.getBoundingClientRect();if(!b.width)return false;const d=Math.min(2,Math.max(1,devicePixelRatio||1));Object.assign(canvas.style,{left:`${b.left-s.left}px`,top:`${b.top-s.top}px`,width:`${b.width}px`,height:`${b.height}px`});canvas.width=Math.round(b.width*d);canvas.height=Math.round(b.height*d);g.viewport(0,0,canvas.width,canvas.height);canvas.dataset.geometryLocked='true';return locked=true}
  function read(){const pieces=[];let to=null;for(const c of board.querySelectorAll('.square[data-square]')){const sq=c.dataset.square,e=c.querySelector('.piece');if(c.classList.contains('last-to'))to=sq;if(!sq||!e||e.hidden||!e.textContent)continue;const type=typeOf(e.textContent.trim());if(!type)continue;pieces.push({square:sq,file:sq.charCodeAt(0)-97,rank:Number(sq[1])-1,type,side:e.classList.contains('white')?'White':'Black'})}return{pieces,lastMove:to}}
  function draw(){if(!lock())return requestAnimationFrame(draw);const state=read(),key=JSON.stringify(state);if(!state.pieces.length||key===last)return;last=key;g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(prog);g.uniformMatrix4fv(u.VP,false,VP);for(const piece of state.pieces){const sc=({Pawn:.73,Knight:.82,Rook:.78,Bishop:.8,Queen:.83,King:.85})[piece.type]||.78,T=multiply(translate(piece.file-3.5,piece.rank-3.85,state.lastMove===piece.square?.08:0),scale(sc,sc,sc)),pal=piece.side==='White'?[[.88,.77,.55],[1,.96,.82],.72]:[[.055,.042,.032],[.48,.34,.2],.88];for(const part of meshes[piece.type]||meshes.Pawn){const M=multiply(T,part.transform);g.uniformMatrix4fv(u.M,false,M);g.uniformMatrix3fv(u.N,false,normal3(M));g.uniform3fv(u.base,pal[0]);g.uniform3fv(u.shine,pal[1]);g.uniform1f(u.gloss,pal[2]);g.bindVertexArray(part.vao);g.drawElements(g.TRIANGLES,part.count,g.UNSIGNED_SHORT,0)}}g.bindVertexArray(null);document.documentElement.classList.add('webgl-3d-ready');canvas.dataset.ready='true';window.CROWNFORGE_WEBGL_READY=true}
  let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;draw()})};new MutationObserver(schedule).observe(board,{attributes:true,attributeFilter:['class','hidden','data-geometry-locked'],childList:true,characterData:true,subtree:true});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();document.documentElement.classList.remove('webgl-3d-ready');document.documentElement.classList.add('webgl-3d-unavailable');window.CROWNFORGE_WEBGL_READY=false});schedule();
}
function typeOf(g){return({'♙':'Pawn','♟':'Pawn','♖':'Rook','♜':'Rook','♘':'Knight','♞':'Knight','♗':'Bishop','♝':'Bishop','♕':'Queen','♛':'Queen','♔':'King','♚':'King'})[g]}
function shader(g,t,s){const x=g.createShader(t);g.shaderSource(x,s);g.compileShader(x);if(!g.getShaderParameter(x,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(x)||'shader error');return x}
function program(g,v,f){const p=g.createProgram(),a=shader(g,g.VERTEX_SHADER,v),b=shader(g,g.FRAGMENT_SHADER,f);g.attachShader(p,a);g.attachShader(p,b);g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p)||'link error');g.deleteShader(a);g.deleteShader(b);return p}
